version: "3"  # Use version 3 or higher for Docker Compose files.

services:
  www:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7.28
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: minipuragem
      MYSQL_USER: minipura
      MYSQL_PASSWORD: minipura
      MYSQL_ROOT_PASSWORD: minipura
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "82:80"
    environment:
      PMA_HOST: db  # Use the service name as the host to connect to the database
      MYSQL_USER: minipura
      MYSQL_PASSWORD: minipura
      MYSQL_ROOT_PASSWORD: minipura
    networks:
      - mynetwork

volumes:
  persistent:

networks:
  mynetwork:
